lsi: false
safe: true
source: ../
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: jekyll-theme-hacker